# controller_mrobot: ['right_Link_joint', 'left_Link_joint', ]
port: /dev/mrobot
baud: 115200
rate: 50
sync_write: True
sync_read: True
read_rate: 50
write_rate: 50

controllers: {
   #  Pololu motors: 1856 cpr = 0.3888105m travel = 4773 ticks per meter (empirical: 4100)
  base_controller:
   {
     type: diff_controller, 
     base_frame_id: base_footprint, 
     base_width: 0.232, 
     ticks_meter: 4100,
     Kp: 12, 
     Kd: 12, 
     Ki: 0, 
     Ko: 50, 
     accel_limit: 0.1 
   }
}
